name: AWS Beanstalk Deployment

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: AWS
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install and Build
      run: |
        cd server
        npm ci
        npm run build --if-present
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: server/
    - name: 'Deploy to AWS Elastic Beanstalk'
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.AWS_APPLICATION_NAME }}
        environment_name: ${{ secrets.AWS_ENVIRONMENT_NAME }}
        version_label: ${{ github.run_number }}
        region: ${{ secrets.AWS_REGION }}
        deployment_package: 'dist.zip'  # This should be the zip file you want to deploy
